services:
    postgres:
        restart: unless-stopped
        image: 'postgres:15'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5432:5432
        volumes:
            - 'postgresData:/var/lib/postgresql/data/'
        networks:
            - dokploy-network

    next:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DATABASE_URL: ${DATABASE_URL}
            COOKIE_SECRET: ${COOKIE_SECRET}
        restart: always
        depends_on:
            postgres:
                condition: service_started
        ports:
            - 3000:3000
        networks:
            - dokploy-network

volumes:
    postgresData: {}

networks:
    dokploy-network:
        external: true
